---
title: "Matrices"
author: "Imanol"
date: "10/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(engine.path = list(matlab = "C:/Archivos de programa/MATLAB/R2020b/bin/matlab.exe"))

library(reticulate)
use_python("../../../anaconda3/envs/Curso Algebra Lineal/python.exe")
```

# R 

## Matrices
```{r}
row = matrix(c(1,2,3,4), nrow = 1) # Para crear una matriz fila
row

col = matrix(c(1,2,3,4), ncol = 1) # Para crear una matriz columna
col

# Creaci贸n de matrices con MATRIX

A = matrix(c(1,1,3,5,2,4,3,-2,-2,2,-1,3), nrow = 3, ncol = 4, byrow = TRUE)
A

B = matrix(c(1,0,2,3,3,2,1,-2,3), nrow = 3, byrow = FALSE)
B

# Creaci贸n de matrices con BIND

C = rbind(c(1,2,3),c(4,5,6),c(7,8,9)) # Por fila
C

D = cbind(c(1,2,3),c(4,5,6),c(7,8,9)) # Por columna
D

# Para acceder a la matriz

A[3,3] # Elemento a33
A[1,]  # Primera fila
A[,2]  # Segunda columna

# Crear matrices de ceros y unos
O = matrix(0, nrow = 3, ncol = 3)
O

Ones = matrix(1, nrow = 3, ncol = 3)
Ones

# Matriz diagonal
E = diag(c(1,2,3,4,5,6))
E

# Para sacar los elementos de la diagonal de una matriz
diag(A)

# Numero de filas y columnas
nrow(A)
ncol(A)
dim(A)
```

## Manipulaci贸n de Matrices
```{r}
sum(A) # Suma todos los elementos de la matriz

# Suma por filas y columnas
rowSums(A)
colSums(A)

# Producto de todos los elementos
prod(A)

# Media
mean(A)
rowMeans(A)
colMeans(A)
```

## Operaciones de Matrices
```{r}
# Traspuesta
A
t(A)

# Calcular traza de la matriz
sum(diag(A))

# Operaciones
A = rbind(c(1,2,3),c(4,5,6),c(7,8,9)) # Por fila
B = rbind(c(1,0,2),c(3,0,4),c(5,0,6)) # Por fila
A+B
5*A
A%*%B # Multiplicar matrices
A*B   # Producto elemento a elemento

# Potencia enesima de una matriz
library(Biodem)
mtx.exp(A,4) # (paquete Biodem)
library(expm)
A%^%4        # (paquete expm)
```


## Rango e inversa de Matrices
```{r}
# Rango
qr(A)$rank

# Inversa
#solve(A)            # Si no existe da un error
#round(A%*%solve(A)) # Para ver que me da la matriz identidad
```

# Python

## Matrices
```{python}
row = [1,2,3] # Para crear una matriz fila
row

col = [[1],[2],[3]] # Para crear una matriz columna
col

 
# Creacion de matrices

M = [[1,2,3],[4,5,6],[7,8,9]]
M

# Para acceder a la matriz

M[1][1] # Elemento a11
M[0][0] # Primera fila primera columna
M[0]    # Primera fila

# Para acceder a las columnas necesitamos numpy

## El manejo es mas comodo con numpy
##antes eran listas en python, ahora si es una matriz
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
## Ademas tiene dtype() con el que podemos elegir el tipo de dato
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex)
print(M)
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
print(M)

## Acceso con numpy
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
M[0][2]
print(M[1])
M[1,:] # Segunda fila
M[:,0] # Primera columna

# Crear matrices de ceros y unos
print(np.zeros((5,7)))
print(np.ones((5,7)))
 

# Matriz diagonal
x = [1,2,3,4]
N = np.diag(x) # Pasando un vector
N

# Para sacar los elementos de la diagonal de una matriz
np.diag(N) # Pasando una matriz


# Numero de filas y columnas
np.shape(M)
```

## Manipulaci贸n de Matrices
```{python}
# Suma todos los elementos de la matriz
np.sum(M)

# Suma por filas y columnas
np.sum(M, axis = 0) # Fila
np.sum(M, axis = 1) # Columna

# Producto de todos los elementos
np.prod(M) # Cuidado con hacer overflow

# Media
np.mean(M) # media de toda la matriz
np.mean(M, axis = 0) # Media por filas
np.mean(M, axis = 1) # Media por columnas
```

## Operaciones de Matrices
```{python}
# Traspuesta
print(M.transpose())

# Calcular traza de la matriz
print(M.trace())

# Suma matrices
A = np.array([[1,2],[2,0]])
B = np.array([[3,0],[1,4]])
print(A+B)

# Producto escalar por matriz
print(5*A)

# Producto de matrices
print(A.dot(B))

# Producto elemento a elemento
print(A*B)

# Potencia de una matriz
print(np.linalg.matrix_power(A,5))
```


## Rango e inversa de Matrices
```{python}
# Rango
np.linalg.matrix_rank(A)
np.linalg.matrix_rank(B)

# Inversa
print(np.linalg.inv(A))
print(np.linalg.inv(A).dot(A)) # Comprobamos (nos deberia dar la matriz identidad)
```

# Matlab

## Matrices
```{matlab}
% Suma de elementos de una matriz
M = [1 2 3; 4 5 6; 7 8 9];
suma = sum(sum(M)) % Primer sum suma por fila y segundo sum por columna

% Suma de elementos por filas y por columnas
M = [1 2 3; 4 5 6; 7 8 9];
sumaFil = sum(M,2)
sumaCol = sum(M,1) % O sumaCol = sum(M)

% Multiplicar elementos de una matriz
M = [1 2 3; 4 5 6; 7 8 9];
producto = prod(prod(M))

% Media
M = [1 2 3; 4 5 6; 7 8 9];
media = mean(mean(M))
mediaFil = mean(M,2)
mediaCol = mean(M,1)
```

## Operaciones con matrices
```{matlab}
% Traspuesta
M = [1 2 3; 4 5 6; 7 8 9];
M'

% Traza de la matriz
A = [1 -1; 0 3];
B = [2 1; -1 0];
trace(A)
trace(B)

% Suma matrices
%Siempre que sean de la misma dimension se pueden llevar a cabo
A = [1 -1; 0 3];
B = [2 1; -1 0];
A+B

% Producto escalar por matrices
A = [1 -1; 0 3];
2*A

% Producto de matrices
A = [1 -1; 0 3];
B = [2 1; -1 0];
A*B

% Potencia de matrices
A = [1 -1; 0 3];
B = [2 1; -1 0];
A^3
B^4
```

## Rango e inversa de Matrices

```{matlab}
% Rango
A = [1 -1; 0 3];
B = [2 1; -1 0];
rank(A)
rank(B)

% Inversa
A = [1 -1; 0 3];
B = [2 1; -1 0];
inv(A)
inv(A)*A % Comprobamos
inv(B)
inv(B)*B % Comprobamos
```